import React, { useEffect, useState } from "react";
import { CATEGORIES } from "../components/CategoryTabs";
import GoogleSignInButton from "../components/GoogleSignInButton";
import TopBar from "../components/TopBar";
import { useAuth } from "../contexts/AuthContext";
import { api } from "../services/api";

function formatDate(value) {
  const date = value ? new Date(value) : null;
  if (!date || Number.isNaN(date.getTime())) return "";
  return date.toLocaleString();
}

export default function Admin() {
  const { user, loading } = useAuth();
  const [msg, setMsg] = useState("");
  const [err, setErr] = useState("");
  const [summBusy, setSummBusy] = useState(false);
  const [dbNews, setDbNews] = useState([]);
  const [liveItems, setLiveItems] = useState([]);

  const [news, setNews] = useState({
    title: "",
    summary: "",
    fullText: "",
    image: "",
    category: "technology",
    source: "",
    url: ""
  });

  const [live, setLive] = useState({ content: "" });

  const canManage = Boolean(user?.isAdmin);

  async function refreshDbNews() {
    const response = await api.get("/news", {
      params: { source: "db", page: 1, limit: 30 }
    });
    setDbNews(response.data?.items || []);
  }

  async function refreshLiveItems() {
    const response = await api.get("/admin/live", {
      params: { page: 1, limit: 20 }
    });
    setLiveItems(response.data?.items || []);
  }

  useEffect(() => {
    if (!user) {
      setDbNews([]);
      setLiveItems([]);
      return;
    }

    refreshDbNews().catch(() => {});
    if (canManage) {
      refreshLiveItems().catch(() => {});
    }
  }, [user, canManage]);

  async function addNews(e) {
    e.preventDefault();
    setErr("");
    setMsg("");

    try {
      const { fullText, ...payload } = news;
      await api.post("/admin/news", payload);
      setMsg("News published successfully!");
      setNews({
        title: "",
        summary: "",
        fullText: "",
        image: "",
        category: "technology",
        source: "",
        url: ""
      });
      await refreshDbNews();
    } catch (e2) {
      setErr(e2?.response?.data?.error || "Failed to add news.");
    }
  }

  async function autoSummarize() {
    setErr("");
    setMsg("");

    const text = news.fullText.trim();
    if (!text) {
      setErr("Paste the full article text first.");
      return;
    }

    setSummBusy(true);
    try {
      const response = await api.post("/admin/summarize", {
        title: news.title || "",
        text
      });
      setNews((current) => ({
        ...current,
        summary: response.data?.summary || current.summary
      }));
      setMsg("Summary generated by AI.");
    } catch (e2) {
      setErr(e2?.response?.data?.error || "Failed to summarize.");
    } finally {
      setSummBusy(false);
    }
  }

  async function addLive(e) {
    e.preventDefault();
    setErr("");
    setMsg("");

    try {
      await api.post("/admin/live", live);
      setMsg("Live update published!");
      setLive({ content: "" });
      await refreshLiveItems();
    } catch (e2) {
      setErr(e2?.response?.data?.error || "Failed to add live update.");
    }
  }

  async function deleteNews(id) {
    setErr("");
    setMsg("");

    try {
      await api.delete(`/admin/news/${id}`);
      setMsg("News deleted.");
      await refreshDbNews();
    } catch (e2) {
      setErr(e2?.response?.data?.error || "Failed to delete news.");
    }
  }

  async function deleteLive(id) {
    setErr("");
    setMsg("");

    try {
      await api.delete(`/admin/live/${id}`);
      setMsg("Live update deleted.");
      await refreshLiveItems();
    } catch (e2) {
      setErr(e2?.response?.data?.error || "Failed to delete live update.");
    }
  }

  const inputClass = "w-full rounded-xl border-zinc-200/60 bg-white px-4 py-2.5 text-sm transition focus:border-brand-400 focus:ring-brand-400 dark:border-white/10 dark:bg-white/5 dark:text-zinc-100";

  return (
    <div className="pb-24">
      <TopBar title="Admin Panel" />

      <main className="page-container py-4">
        {loading ? (
          <div className="flex items-center justify-center gap-2 py-8">
            <div className="h-5 w-5 animate-spin rounded-full border-2 border-brand-500 border-t-transparent" />
            <span className="text-sm text-zinc-500 dark:text-zinc-400">Loading...</span>
          </div>
        ) : null}

        {!loading && !user ? (
          <div className="glass-card p-6 text-center animate-fade-in">
            <div className="mx-auto mb-3 text-4xl">🔐</div>
            <div className="mb-4 text-sm text-zinc-600 dark:text-zinc-300">
              Sign in to access admin tools.
            </div>
            <GoogleSignInButton className="mx-auto max-w-xs" />
          </div>
        ) : null}

        {msg ? (
          <div className="mb-4 rounded-2xl border border-emerald-200/60 bg-emerald-50/80 p-4 text-sm text-emerald-800 dark:border-emerald-500/10 dark:bg-emerald-500/5 dark:text-emerald-200 animate-slide-up">
            ✅ {msg}
          </div>
        ) : null}

        {err ? (
          <div className="mb-4 rounded-2xl border border-red-200/60 bg-red-50/80 p-4 text-sm text-red-700 dark:border-red-500/10 dark:bg-red-500/5 dark:text-red-200 animate-slide-up">
            ❌ {err}
          </div>
        ) : null}

        {user && !canManage ? (
          <div className="glass-card p-4 text-sm text-amber-700 dark:text-amber-300 animate-fade-in">
            ⚠️ This account is signed in but not allowlisted for admin actions. Add your email to{" "}
            <code className="rounded bg-zinc-100 px-1.5 py-0.5 text-xs dark:bg-white/5">ADMIN_EMAILS</code> in{" "}
            <code className="rounded bg-zinc-100 px-1.5 py-0.5 text-xs dark:bg-white/5">backend/.env</code>.
          </div>
        ) : null}

        {canManage ? (
          <div className="space-y-4 animate-fade-in">
            {/* Add News */}
            <section className="glass-card p-5">
              <div className="flex items-center gap-2 text-sm font-bold">
                <span>📝</span> Add News Article
              </div>

              <form onSubmit={addNews} className="mt-4 space-y-3">
                <input
                  className={inputClass}
                  placeholder="Title"
                  value={news.title}
                  onChange={(e) => setNews((current) => ({ ...current, title: e.target.value }))}
                />

                <textarea
                  className={inputClass}
                  placeholder="Summary (50-70 words)"
                  rows={4}
                  value={news.summary}
                  onChange={(e) => setNews((current) => ({ ...current, summary: e.target.value }))}
                />

                <textarea
                  className={inputClass}
                  placeholder="Full article text for auto-summary (optional)"
                  rows={5}
                  value={news.fullText}
                  onChange={(e) => setNews((current) => ({ ...current, fullText: e.target.value }))}
                />

                <button
                  type="button"
                  onClick={autoSummarize}
                  disabled={summBusy || !news.fullText.trim()}
                  className="btn-secondary disabled:opacity-50"
                >
                  {summBusy ? "⏳ Summarizing..." : "🤖 Auto-summarize"}
                </button>

                <input
                  className={inputClass}
                  placeholder="Image URL"
                  value={news.image}
                  onChange={(e) => setNews((current) => ({ ...current, image: e.target.value }))}
                />

                <div className="flex gap-2">
                  <select
                    className={inputClass}
                    value={news.category}
                    onChange={(e) => setNews((current) => ({ ...current, category: e.target.value }))}
                  >
                    {CATEGORIES.filter((category) => category.key !== "all").map((category) => (
                      <option key={category.key} value={category.key}>
                        {category.label}
                      </option>
                    ))}
                  </select>

                  <input
                    className={inputClass}
                    placeholder="Source name"
                    value={news.source}
                    onChange={(e) => setNews((current) => ({ ...current, source: e.target.value }))}
                  />
                </div>

                <input
                  className={inputClass}
                  placeholder="Source URL"
                  value={news.url}
                  onChange={(e) => setNews((current) => ({ ...current, url: e.target.value }))}
                />

                <button
                  type="submit"
                  className="btn-primary w-full"
                >
                  🚀 Publish Article
                </button>
              </form>
            </section>

            {/* Add Live Update */}
            <section className="glass-card p-5">
              <div className="flex items-center gap-2 text-sm font-bold">
                <span>📡</span> Add Live Update
              </div>

              <form onSubmit={addLive} className="mt-4 space-y-3">
                <textarea
                  className={inputClass}
                  placeholder="Breaking update text..."
                  rows={3}
                  value={live.content}
                  onChange={(e) => setLive({ content: e.target.value })}
                />

                <button
                  type="submit"
                  className="btn-primary w-full"
                >
                  ⚡ Publish Live Update
                </button>
              </form>
            </section>

            {/* Recent DB News */}
            <section className="glass-card p-5">
              <div className="flex items-center gap-2 text-sm font-bold">
                <span>📋</span> Recent DB Articles
              </div>

              <div className="mt-4 space-y-2">
                {dbNews.map((item) => (
                  <div
                    key={item._id || item.url}
                    className="flex items-start justify-between gap-3 rounded-xl border border-zinc-100 bg-zinc-50/50 p-3 transition hover:bg-zinc-100/50 dark:border-white/5 dark:bg-white/[0.02] dark:hover:bg-white/5"
                  >
                    <div className="min-w-0">
                      <div className="truncate text-sm font-semibold">{item.title}</div>
                      <div className="truncate text-xs text-zinc-500 dark:text-zinc-400">
                        {item.category} · {item.provider} · {formatDate(item.publishedAt)}
                      </div>
                    </div>
                    {item._id ? (
                      <button
                        type="button"
                        onClick={() => deleteNews(item._id)}
                        className="btn-secondary shrink-0 !px-3 !py-1.5 !text-xs text-red-600 hover:!border-red-200 hover:!bg-red-50 hover:!text-red-700 dark:text-red-400"
                      >
                        🗑️ Delete
                      </button>
                    ) : null}
                  </div>
                ))}

                {dbNews.length === 0 ? (
                  <div className="text-sm text-zinc-500 dark:text-zinc-400">
                    No manual or saved DB articles yet.
                  </div>
                ) : null}
              </div>
            </section>

            {/* Recent Live Updates */}
            <section className="glass-card p-5">
              <div className="flex items-center gap-2 text-sm font-bold">
                <span>🔴</span> Recent Live Updates
              </div>

              <div className="mt-4 space-y-2">
                {liveItems.map((item) => (
                  <div
                    key={item._id}
                    className="flex items-start justify-between gap-3 rounded-xl border border-zinc-100 bg-zinc-50/50 p-3 transition hover:bg-zinc-100/50 dark:border-white/5 dark:bg-white/[0.02] dark:hover:bg-white/5"
                  >
                    <div className="min-w-0">
                      <div className="text-sm text-zinc-800 dark:text-zinc-100">{item.content}</div>
                      <div className="mt-1 text-xs text-zinc-500 dark:text-zinc-400">
                        {formatDate(item.timestamp)}
                      </div>
                    </div>
                    <button
                      type="button"
                      onClick={() => deleteLive(item._id)}
                      className="btn-secondary shrink-0 !px-3 !py-1.5 !text-xs text-red-600 hover:!border-red-200 hover:!bg-red-50 hover:!text-red-700 dark:text-red-400"
                    >
                      🗑️ Delete
                    </button>
                  </div>
                ))}

                {liveItems.length === 0 ? (
                  <div className="text-sm text-zinc-500 dark:text-zinc-400">
                    No live updates yet.
                  </div>
                ) : null}
              </div>
            </section>
          </div>
        ) : null}
      </main>
    </div>
  );
}
